#####################################################################
#       Complete Configuration for NV Simulator and Optimization      #
#####################################################################
# This file contains a full configuration setup for using the NV
# simulator with the optimization modules.

global:
    # Define default data storage path
    default_data_dir: ~/qudi-data
    # Define a default "work directory"
    work_dir: ~/qudi-work

hardware:
    # No hardware modules needed for simulation mode

logic:
    # NV Simulator Logic
    nv_simulator:
        module.Class: 'logic.nv_simulator_logic.NVSimulatorLogic'
        
        # Physical parameters
        d_gs: 2.87e9       # Zero-field splitting (Hz)
        e_gs: 2e6          # Strain parameter (Hz)
        gamma_e: 28e6      # Gyromagnetic ratio (Hz/mT)
        b_field: [0, 0, 0.5] # External B field (mT) [Bx, By, Bz]
        t1: 100e-6         # T1 relaxation time (s)
        t2: 50e-6          # T2 relaxation time (s)
        noise_level: 0.05  # Measurement noise level
        initial_state: [1, 0, 0]  # |0⟩ state as default

    # Worker modules for Optimization Logic
    worker_fom:
        module.Class: 'logic.optimalcontrol.worker_fom.WorkerFom'
    
    worker_controls:
        module.Class: 'logic.optimalcontrol.worker_controls.WorkerControls'
    
    # Optimization Logic
    optimization:
        module.Class: 'logic.optimalcontrol.OptimizationLogic'
        connect:
            fom_logic: worker_fom
            controls_logic: worker_controls
            # Comment out these if you don't have qudi-iqo-modules
            # pulser_dummy: dummy_pulser
            # optimizer_dummy: dummy_optimizer
        
        # Optional: Add path to default configuration file
        # quocs_default_config: '~/qudi-config/quocs_default.json'

gui:
    # NV Simulator GUI
    nv_simulator_gui:
        module.Class: 'gui.optimalcontrol.NVSimulatorGUI'
        connect:
            nv_simulator_logic: nv_simulator

    # Optimization GUI
    optimization_gui:
        module.Class: 'gui.optimalcontrol.OptimizationGUI'
        connect:
            optimization_logic: optimization