##############################################################################
#                   Sample Qudi Configuration File                            #
##############################################################################
# This is a complete configuration file for using both the NV simulator and 
# optimization modules in Qudi. Copy and paste this into your Qudi config.

global:
    # Define default data storage path
    default_data_dir: ~/qudi-data
    # Define a default "work directory"
    work_dir: ~/qudi-work
    # Default log level, can be {'debug', 'info', 'warning', 'error', 'critical'}
    log_level: debug

gui:
    # NV Simulator GUI
    nv_simulator_gui:
        module.Class: 'qudi.gui.optimalcontrol.NVSimulatorGUI'
        connect:
            nv_simulator_logic: nv_simulator

    # Optimization GUI
    optimization_gui:
        module.Class: 'qudi.gui.optimalcontrol.OptimizationGUI'
        connect:
            optimization_logic: optimization

logic:
    # NV Simulator Logic
    nv_simulator:
        module.Class: 'qudi.logic.nv_simulator_logic.NVSimulatorLogic'
        
        # Physical parameters
        d_gs: 2.87e9       # Zero-field splitting (Hz)
        e_gs: 2e6          # Strain parameter (Hz)
        gamma_e: 28e6      # Gyromagnetic ratio (Hz/mT)
        b_field: [0, 0, 0.5] # External B field (mT) [Bx, By, Bz]
        t1: 100e-6         # T1 relaxation time (s)
        t2: 50e-6          # T2 relaxation time (s)
        noise_level: 0.05  # Measurement noise level
        initial_state: [1, 0, 0]  # |0⟩ state as default

    # Worker modules for Optimization Logic
    worker_fom:
        module.Class: 'qudi.logic.optimalcontrol.worker_fom.WorkerFom'
    
    worker_controls:
        module.Class: 'qudi.logic.optimalcontrol.worker_controls.WorkerControls'
    
    # Optimization Logic
    optimization:
        module.Class: 'qudi.logic.optimalcontrol.OptimizationLogic'
        connect:
            fom_logic: worker_fom
            controls_logic: worker_controls